In [1]:
import pandas as pd

In [5]:
data = pd.read_csv('001.csv', index_col=0)

In [6]:
data

,baseball,economics,politics,Europe,Asia,soccer,war,security,shopping,family,User 1,User 2
doc1,1,0,1,0,1,1,0,0,0,1,1.0,-1.0
doc2,0,1,1,1,0,0,0,1,0,0,-1.0,1.0
doc3,0,0,0,1,1,1,0,0,0,0,NaN,NaN
doc4,0,0,1,1,0,0,1,1,0,0,NaN,1.0
doc5,0,1,0,0,0,0,0,0,1,1,NaN,NaN
doc6,1,0,0,1,0,0,0,0,0,0,1.0,NaN
doc7,0,0,0,0,0,0,0,1,0,1,NaN,NaN
doc8,0,0,1,1,0,0,1,0,0,1,NaN,NaN
doc9,0,0,0,0,0,1,0,0,1,0,NaN,NaN
doc10,0,1,0,0,1,0,1,0,0,0,NaN,NaN
doc11,0,0,1,0,1,0,0,0,1,0,NaN,NaN
doc12,1,0,0,0,0,1,1,0,0,0,NaN,-1.0
doc13,0,0,1,1,1,0,0,1,0,0,NaN,NaN
doc14,0,1,1,1,0,0,0,0,1,0,NaN,NaN
doc15,0,0,0,1,0,1,1,1,0,0,NaN,NaN
doc16,1,0,0,0,0,1,0,0,1,0,1.0,NaN
doc17,0,1,1,1,0,0,0,1,0,0,NaN,1.0
doc18,0,0,0,1,0,0,0,0,1,0,NaN,NaN
doc19,0,1,1,0,1,0,1,0,0,1,-1.0,NaN
doc20,0,0,1,1,0,0,1,0,1,0,NaN,NaN

In [9]:
features = data[data.columns[0:10]]

In [10]:
features

,baseball,economics,politics,Europe,Asia,soccer,war,security,shopping,family
doc1,1,0,1,0,1,1,0,0,0,1
doc2,0,1,1,1,0,0,0,1,0,0
doc3,0,0,0,1,1,1,0,0,0,0
doc4,0,0,1,1,0,0,1,1,0,0
doc5,0,1,0,0,0,0,0,0,1,1
doc6,1,0,0,1,0,0,0,0,0,0
doc7,0,0,0,0,0,0,0,1,0,1
doc8,0,0,1,1,0,0,1,0,0,1
doc9,0,0,0,0,0,1,0,0,1,0
doc10,0,1,0,0,1,0,1,0,0,0
doc11,0,0,1,0,1,0,0,0,1,0
doc12,1,0,0,0,0,1,1,0,0,0
doc13,0,0,1,1,1,0,0,1,0,0
doc14,0,1,1,1,0,0,0,0,1,0
doc15,0,0,0,1,0,1,1,1,0,0
doc16,1,0,0,0,0,1,0,0,1,0
doc17,0,1,1,1,0,0,0,1,0,0
doc18,0,0,0,1,0,0,0,0,1,0
doc19,0,1,1,0,1,0,1,0,0,1
doc20,0,0,1,1,0,0,1,0,1,0

In [18]:
user1_prefer = (features.T * data['User 1']).sum(axis = 1)

In [19]:
user1_prefer

baseball     3.0
economics   -2.0
politics    -1.0
Europe       0.0
Asia         0.0
soccer       2.0
war         -1.0
security    -1.0
shopping     1.0
family       0.0
dtype: float64

In [20]:
user2_prefer = (features.T * data['User 2']).sum(axis = 1)

In [21]:
user2_prefer

baseball    -2.0
economics    2.0
politics     2.0
Europe       3.0
Asia        -1.0
soccer      -2.0
war          0.0
security     3.0
shopping     0.0
family      -1.0
dtype: float64

In [27]:
user1_doc = (features * user1_prefer).sum(axis = 1)

In [30]:
user1_doc.sort_values(ascending=False)

doc16    6.0
doc1     4.0
doc12    4.0
doc9     3.0
doc6     3.0
doc3     2.0
doc18    1.0
doc15    0.0
doc11    0.0
doc5    -1.0
doc7    -1.0
doc20   -1.0
doc8    -2.0
doc13   -2.0
doc14   -2.0
doc4    -3.0
doc10   -3.0
doc19   -4.0
doc17   -4.0
doc2    -4.0
dtype: float64

In [33]:
user2_doc = (features * user2_prefer).sum(axis = 1)

In [34]:
user2_doc.sort_values(ascending=False)

doc17    10.0
doc2     10.0
doc4      8.0
doc14     7.0
doc13     7.0
doc20     5.0
doc15     4.0
doc8      4.0
doc18     3.0
doc7      2.0
doc19     2.0
doc5      1.0
doc6      1.0
doc10     1.0
doc11     1.0
doc3      0.0
doc9     -2.0
doc12    -4.0
doc16    -4.0
doc1     -4.0
dtype: float64

In [43]:
norm_features = features.T/ (features.sum(axis = 1) ** (1/2))

In [79]:
norm_features

,doc1,doc2,doc3,doc4,doc5,doc6,doc7,doc8,doc9,doc10,doc11,doc12,doc13,doc14,doc15,doc16,doc17,doc18,doc19,doc20
baseball,0.447214,0.0,0.00000,0.0,0.00000,0.707107,0.000000,0.0,0.000000,0.00000,0.00000,0.57735,0.0,0.0,0.0,0.57735,0.0,0.000000,0.000000,0.0
economics,0.000000,0.5,0.00000,0.0,0.57735,0.000000,0.000000,0.0,0.000000,0.57735,0.00000,0.00000,0.0,0.5,0.0,0.00000,0.5,0.000000,0.447214,0.0
politics,0.447214,0.5,0.00000,0.5,0.00000,0.000000,0.000000,0.5,0.000000,0.00000,0.57735,0.00000,0.5,0.5,0.0,0.00000,0.5,0.000000,0.447214,0.5
Europe,0.000000,0.5,0.57735,0.5,0.00000,0.707107,0.000000,0.5,0.000000,0.00000,0.00000,0.00000,0.5,0.5,0.5,0.00000,0.5,0.707107,0.000000,0.5
Asia,0.447214,0.0,0.57735,0.0,0.00000,0.000000,0.000000,0.0,0.000000,0.57735,0.57735,0.00000,0.5,0.0,0.0,0.00000,0.0,0.000000,0.447214,0.0
soccer,0.447214,0.0,0.57735,0.0,0.00000,0.000000,0.000000,0.0,0.707107,0.00000,0.00000,0.57735,0.0,0.0,0.5,0.57735,0.0,0.000000,0.000000,0.0
war,0.000000,0.0,0.00000,0.5,0.00000,0.000000,0.000000,0.5,0.000000,0.57735,0.00000,0.57735,0.0,0.0,0.5,0.00000,0.0,0.000000,0.447214,0.5
security,0.000000,0.5,0.00000,0.5,0.00000,0.000000,0.707107,0.0,0.000000,0.00000,0.00000,0.00000,0.5,0.0,0.5,0.00000,0.5,0.000000,0.000000,0.0
shopping,0.000000,0.0,0.00000,0.0,0.57735,0.000000,0.000000,0.0,0.707107,0.00000,0.57735,0.00000,0.0,0.5,0.0,0.57735,0.0,0.707107,0.000000,0.5
family,0.447214,0.0,0.00000,0.0,0.57735,0.000000,0.707107,0.5,0.000000,0.00000,0.00000,0.00000,0.0,0.0,0.0,0.00000,0.0,0.000000,0.447214,0.0

In [47]:
norm_user1_prefer = (norm_features * data['User 1']).sum(axis  =1)

In [49]:
norm_user1_prefer

baseball     1.731671
economics   -0.947214
politics    -0.500000
Europe       0.207107
Asia         0.000000
soccer       1.024564
war         -0.447214
security    -0.500000
shopping     0.577350
family       0.000000
dtype: float64

In [48]:
norm_user2_prefer = (norm_features * data['User 2']).sum(axis  =1)

In [50]:
norm_user2_prefer

baseball    -1.024564
economics    1.000000
politics     1.052786
Europe       1.500000
Asia        -0.447214
soccer      -1.024564
war         -0.077350
security     1.500000
shopping     0.000000
family      -0.447214
dtype: float64

In [53]:
norm_user1_doc = (norm_features.T * norm_user1_prefer).sum(axis = 1)

In [57]:
norm_user1_doc.sort_values(ascending=False)

doc16    1.924646
doc6     1.370923
doc12    1.333114
doc9     1.132724
doc1     1.009019
doc3     0.711105
doc18    0.554695
doc15    0.142229
doc11    0.044658
doc20   -0.081378
doc5    -0.213541
doc14   -0.331378
doc7    -0.353553
doc8    -0.370053
doc13   -0.396447
doc4    -0.620053
doc10   -0.805073
doc19   -0.847214
doc17   -0.870053
doc2    -0.870053
dtype: float64

In [55]:
norm_user2_doc = (norm_features.T * norm_user2_prefer).sum(axis = 1)

In [58]:
norm_user2_doc.sort_values(ascending=False)

doc17    2.526393
doc2     2.526393
doc4     1.987718
doc13    1.802786
doc14    1.776393
doc20    1.237718
doc18    1.060660
doc8     1.014111
doc15    0.949043
doc7     0.744432
doc19    0.483442
doc11    0.349628
doc6     0.336184
doc5     0.319151
doc10    0.274493
doc3     0.016294
doc9    -0.724476
doc1    -0.845577
doc16   -1.183064
doc12   -1.227723
dtype: float64

In [59]:
DF = features.sum()

In [63]:
import numpy as np

In [74]:
IDF = 1/DF

In [75]:
IDF

baseball     0.250000
economics    0.166667
politics     0.100000
Europe       0.090909
Asia         0.166667
soccer       0.166667
war          0.142857
security     0.166667
shopping     0.142857
family       0.200000
dtype: float64

In [77]:
(norm_features.T * norm_user1_prefer * IDF).sum(axis = 1).sort_values(ascending = False)

doc16    0.396153
doc6     0.319432
doc12    0.311648
doc1     0.247612
doc9     0.179067
doc3     0.109459
doc18    0.071635
doc15    0.021184
doc11    0.018752
doc20   -0.006291
doc5    -0.043527
doc8    -0.047530
doc14   -0.053281
doc13   -0.057253
doc7    -0.058926
doc4    -0.089197
doc19   -0.121533
doc10   -0.128031
doc17   -0.136187
doc2    -0.136187
dtype: float64

In [78]:
(norm_features.T * norm_user2_prefer * IDF).sum(axis = 1).sort_values(ascending = False)

doc17    0.329154
doc2     0.329154
doc4     0.240296
doc13    0.208553
doc14    0.204154
doc20    0.115296
doc7     0.113531
doc15    0.102276
doc18    0.096424
doc8     0.070575
doc10    0.046812
doc5     0.044585
doc19    0.043343
doc11    0.017750
doc3    -0.062892
doc6    -0.084695
doc9    -0.120746
doc1    -0.217167
doc16   -0.246472
doc12   -0.252852
dtype: float64